coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
    patch:
      default:
        target: 70%

comment:
  layout: "condensed_header, condensed_files"
  require_changes: true
