name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe what you'd like.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you'd like.
      placeholder: I'd like to be able to...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What problem does this solve? How would you use it?
      placeholder: Currently I have to... but with this feature I could...
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Related Module
      description: Which module would this feature belong to?
      options:
        - Email
        - Calendar
        - Contacts
        - Categories
        - Settings
        - Folder
        - Rules
        - Advanced
        - Auth
        - New Module
        - Other
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this working?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information or examples.
